# -*- coding: utf-8 -*-
"""08-02-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15seBvaOUo4LM28i_LFOs_3lknBIVEDZz
"""

print("i am going \n college")

print("i am going \n college for\t learning nlp")

print("i am going \n college for\r learning nlp")

import re

string="007 james bond wants to learn python"
pattern=r'\d+'
matching=re.match(pattern,string)
matching.group()

string="james bond wants  007 to learn  008python"
pattern=r'\d+'
matching=re.search(pattern,string)
matching.group()

string="007 james bond  008 wants to 009 learn python"
pattern=r'\d+'
matching=re.findall(pattern,string)
matching

string="007 james  ***bond    ***008 wants to 009 learn python"
pattern=r'\d+'
matching=re.sub(pattern,'#',string)
matching

import re
from bs4 import BeautifulSoup

def clean_text(text):
    # Extract email addresses
    emails = re.findall(r'[\w\.-]+@[\w\.-]+', text)

    # Extract hashtags
    hashtags = re.findall(r'#[A-Za-z0-9_]+', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove HTML tags
    text = BeautifulSoup(text, 'html.parser').get_text()

    # Normalize whitespace
    text = ' '.join(text.split())

    return text, emails, hashtags

# Test case
text = """
Hello world! Contact us at info@example.com or support123@company.org.
Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with nu
"""

cleaned_text, extracted_emails, extracted_hashtags = clean_text(text)

print("Cleaned Text:", cleaned_text)
print("Extracted Emails:", extracted_emails)
print("Extracted Hashtags:", extracted_hashtags)

text = """
Hello world! Contact us at info@example.com or support123@company.org.
Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with nu
"""
pattern=r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
emails=re.findall(pattern,text)
emails

text = """
Hello world! Contact us at info@example.com or support123@company.org.
Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with nu
"""
hashtags = re.findall(r'#[A-Za-z0-9_]+', text)
hashtags

