# -*- coding: utf-8 -*-
"""day 1,2,3,4 assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZLEni0omzYEXW9ExC4zhT_yT_guIPFD
"""

#day1 assignment
# Declaring variables of different data types
integer_var = 42               # Integer
float_var = 3.14               # Float
string_var = "Hello, Jupyter!" # String
boolean_var = True             # Boolean

# Printing each variable and its type
print("Integer value:", integer_var, " | Type:", type(integer_var))
print("Float value:", float_var, " | Type:", type(float_var))
print("String value:", string_var, " | Type:", type(string_var))
print("Boolean value:", boolean_var, " | Type:", type(boolean_var))

#day2 assignment
# List example
my_list = [10, 20, 30, 40, 50]
print("List:", my_list)

# Accessing elements in a list
print("First element in list:", my_list[0])   # Index 0
print("Last element in list:", my_list[-1])  # Negative index
print("Slice of list (2nd to 4th):", my_list[1:4])  # Slicing

# Tuple example
my_tuple = ("apple", "banana", "cherry", "date", "elderberry")
print("\nTuple:", my_tuple)

# Accessing elements in a tuple
print("Second element in tuple:", my_tuple[1])   # Index 1
print("Last element in tuple:", my_tuple[-1])   # Negative index
print("Slice of tuple (3rd to last):", my_tuple[2:])  # Slicing

# Dictionary example
my_dict = {
    "name": "Alice",
    "age": 25,
    "city": "New York",
    "profession": "Engineer",
    "hobby": "Reading"
}
print("\nDictionary:", my_dict)

# Accessing elements in a dictionary
print("Access 'name':", my_dict["name"])         # Accessing by key
print("Access 'city':", my_dict["city"])         # Accessing by key
print("All keys:", list(my_dict.keys()))         # Getting all keys
print("All values:", list(my_dict.values()))     # Getting all values

#day3 assignment
# Taking input for marks in three subjects
subject1 = float(input("Enter marks for Subject 1: "))
subject2 = float(input("Enter marks for Subject 2: "))
subject3 = float(input("Enter marks for Subject 3: "))

# Calculating the average
average = (subject1 + subject2 + subject3) / 3

# Determining the grade
if average >= 90:
    grade = "A"
elif 80 <= average < 90:
    grade = "B"
elif 70 <= average < 80:
    grade = "C"
else:
    grade = "Fail"

# Printing the result
print(f"Average Marks: {average:.2f}")
print(f"Grade: {grade}")

#day4 assignment
# Input: A positive integer n
n = int(input("Enter a positive integer: "))

# Calculate the sum of all even numbers between 1 and n
even_sum = sum(number for number in range(2, n+1, 2))

# Output the result
print(f"The sum of all even numbers between 1 and {n} is: {even_sum}")