# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp4VO-fNJ7WwkJD4toUX61u7wed9nvsT
"""

a="Lavanya"
print(a)

a=[1,2,9,5,6]
print(a)
print(a[2])

#Hetrogenous elements
a=[1,"Hi",9.00,True,[0,1,2,"hello"]]
print(a)
print(a[4])

a="hi"
b=a
print(a)
print(b)

a=[1,2,3,4,5]
b=a
print(a,b)

#slicing
a=[10,20,30,40,50,60,70,80,90]
print(a[1:4])
print(a[:5])
print(a[5:])
print(a[2:8:3])
print(a[-5:-2])
print(a[1::3])
print(a[::1])
print(a[::2])
print(a[::3])
print(a[::4])

a=[10,20,30,40,50,60,70,80,90]
a=b
print(a[:3])
print(b)